### ISSUE TITLE
ImportError: cannot import name 'logsumexp' with sklearn >= 0.23.0

### ISSUE THREAD

**Issue by thgoebel** [scikit-learn-contrib/metric-learn#292]
#### Description
`ImportError` with scikit-learn >= 0.23.0. Works fine with scikit-learn <= 0.22.2.

I looked around and I think could be due to [this change](https://github.com/scikit-learn/scikit-learn/commit/75d3f29e724c9a2db7bcb5afb2d7e8c08ddbd80b#diff-329170b5852c0662b9d3e1a950663801).

#### Steps/Code to Reproduce
```python
>>> from metric_learn import MMC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/workspace/venv/lib/python3.6/site-packages/metric_learn/__init__.py", line 9, in <module>
    from .nca import NCA
  File "/home/user/workspace/venv/lib/python3.6/site-packages/metric_learn/nca.py", line 13, in <module>
    from sklearn.utils.fixes import logsumexp
ImportError: cannot import name 'logsumexp'
```

#### Expected Results

No error is thrown.

#### Actual Results

ImportError is thrown.

#### Versions

```
>>> import platform; print(platform.platform())
Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import sys; print("Python", sys.version)
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.18.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.4.1
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 0.23.1
>>> import metric_learn; print("Metric-Learn", metric_learn.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/workspace/venv/lib/python3.6/site-packages/metric_learn/__init__.py", line 9, in <module>
    from .nca import NCA
  File "/home/ùser/workspace/venv/lib/python3.6/site-packages/metric_learn/nca.py", line 13, in <module>
    from sklearn.utils.fixes import logsumexp
ImportError: cannot import name 'logsumexp'
```

```
(venv) $ pip list --format columns
Package         Version
--------------- -------
joblib          0.15.1 
metric-learn    0.5.0  
numpy           1.18.4 
pandas          1.0.3  
patsy           0.5.1  
Pillow          7.1.2  
pip             9.0.1  
pkg-resources   0.0.0  
python-dateutil 2.8.1  
pytz            2020.1 
scikit-learn    0.23.1 
scipy           1.4.1  
setuptools      39.0.1 
six             1.15.0 
sklearn         0.0    
statsmodels     0.11.1 
threadpoolctl   2.0.0 
```

**Comment by thgoebel** [comment]
Dupe of https://github.com/scikit-learn-contrib/metric-learn/issues/289, sorry. Gosh I hate that Github doesn't show closed issue by default in their search,

**Comment by perimosocordiae** [comment]
No worries, it happens. Also that's an impressively detailed issue description-- please file more if you find something else! :-)

**Comment by thgoebel** [comment]
Just following your issue template :)
